import React from 'react';
import Navbar from '@/components/Navbar';
import Footer from '@/components/HomePage/Footer';

const TermsPage = () => {
  return (
    <div className="min-h-screen bg-black text-white selection:bg-[#FAB614] selection:text-black font-sans flex flex-col">
      {/* Background decoration */}
      <div className="fixed inset-0 pointer-events-none overflow-hidden">
        <div className="absolute top-0 right-0 w-[1000px] h-[450px] bg-[#E5970C]/20 blur-[100px] rounded-full" />
      </div>
      
      <Navbar />

      <div className="flex-grow container mx-auto px-4 pt-32 pb-20">
        <div className="max-w-5xl mx-auto">
          <div className="text-center mb-12">
            <h1 className="text-4xl md:text-6xl font-extrabold text-[#FAB614] uppercase tracking-wider mb-8">
              Terms & Conditions
            </h1>
          </div>

          {/* Terms Content */}
          <div className="text-gray-300 space-y-6 leading-relaxed text-lg text-justify md:text-left">
            
            {/* 1. INTRODUCTION */}
            <h2 className="text-2xl font-bold text-[#FAB614] mt-12 mb-6 uppercase">1. INTRODUCTION</h2>
            <p>
              This Agreement governs your use of the CineCertified Digital Logbook Application (the “App”), operated by CineCertified CIC (“CineCertified”, “we”, “our”, or “us”), a Community Interest Company registered in England and Wales (company number 16080111), with the registered address of: Flat 4, 34 Churchfield Road, London W3 6EB.
            </p>
            <p>
              By downloading, installing, accessing, or using the App, the User (“User” or “you”) agrees to be bound by these Terms and Conditions (the “Agreement”). If the User does not agree, they must not use the App.
            </p>
            <p>
              Use of the App is also subject to the Google Play Developer Distribution Agreement and Apple App Store Terms of Service, as applicable to the User’s device.
            </p>

            {/* 2. DEFINITION OF CONTENT */}
            <h2 className="text-2xl font-bold text-[#FAB614] mt-12 mb-6 uppercase">2. DEFINITION OF CONTENT</h2>
            <ul className="space-y-4">
              <li>
                <span className="text-white font-bold">“App”</span> means the CineCertified Digital Logbook mobile application and any associated services, websites, and databases.
              </li>
              <li>
                <span className="text-white font-bold">“CineCertified Content”</span> means all materials owned, created, or licensed by CineCertified, including the CineCertified framework, training content, structure, graphics, images, videos, audio, and data systems.
              </li>
              <li>
                <span className="text-white font-bold">“Content”</span> refers to all text, data, graphics, video, images, software, code, documentation, and materials or any other information made available through the App or any associated services, websites or databases, including both CineCertified Content and User Content.
              </li>
              <li>
                <span className="text-white font-bold">“Data Controller”</span> refers to the person or company that controls the use of Data, Personal and otherwise, that is uploaded to and/or used by the App.
              </li>
              <li>
                <span className="text-white font-bold">“Personal Data”</span> means any data that identifies an individual, as defined under the UK General Data Protection Regulation (GDPR) and the Data Protection Act 2018.
              </li>
              <li>
                <span className="text-white font-bold">“Services”</span> means all features, functionality, and related platforms made available by CineCertified through the App.
              </li>
              <li>
                <span className="text-white font-bold">“Third-Party Providers”</span> means external companies delivering optional courses or materials within or linked from the App, for example, but not limited to: Train2Save and the Mark Milsome Foundation.
              </li>
              <li>
                <span className="text-white font-bold">“User”</span> refers to the person who has signed up to the CineCertified App and framework, as a Trainee, Signatory and/or Ambassador.
              </li>
              <li>
                <span className="text-white font-bold">“User Content”</span> means materials uploaded, submitted, or generated by users through the use of the App, such as profile data, images, comments, or logbook records.
              </li>
            </ul>

            {/* 3. ELIGIBILITY AND ACCESS */}
            <h2 className="text-2xl font-bold text-[#FAB614] mt-12 mb-6 uppercase">3. ELIGIBILITY AND ACCESS</h2>
            <p>
              You must be at least thirteen (13) years of age to create an account and to use the Digital Logbook App. This is in line with the UK General Data Protection Regulation (GDPR) laws. Your use of the Digital Logbook App and its content must follow the rules set forth in this section, herein referred to as “Usage Rules”.
            </p>
            <p>
              Any other use of the CineCertified logbook app and its content is a material breach of this agreement. CineCertified may monitor your use of the logbook app in order to ensure that you are adhering to the Usage Rules.
            </p>

            {/* 4. LICENCE */}
            <h2 className="text-2xl font-bold text-[#FAB614] mt-12 mb-6 uppercase">4. LICENCE</h2>
            <p>
              CineCertified grants you a limited, non-exclusive, revocable, non-transferable licence to access and use the App for your own educational, non-commercial purposes within the CineCertified framework.
            </p>
            <p>
              This licence does not grant ownership or any rights to the App or its Content. You must not copy, modify, reproduce, sell, lease, reverse engineer, decompile, or create derivative works of the App or any part of its Content. All rights not expressly granted to you remain reserved by CineCertified.
            </p>

            {/* 5. USER RESPONSIBILITY & USAGE RULES */}
            <h2 className="text-2xl font-bold text-[#FAB614] mt-12 mb-6 uppercase">5. USER RESPONSIBILITY & USAGE RULES</h2>
            <p>
              You agree to provide accurate, up-to-date information in your profile and logbook; use the App only for lawful, educational purposes; and comply with all applicable UK and international laws, including data-protection and intellectual-property laws. For all users of the App, the following terms are applicable:
            </p>
            <ul className="list-disc pl-6 space-y-2 mb-6">
              <li>You may use the CineCertified logbook app and its content for personal, non-commercial use only.</li>
              <li>Use of the CineCertified logbook app does not transfer any commercial or promotional use rights to you, and does not constitute a grant or waiver of any rights of the copyright owners.</li>
              <li>You may not manipulate the use of the CineCertified logbook app via any means, including but not limited to: completing key learning points within camera skills, signing off on stages of camera skills – such as (a) using a bot, script or automated process; or (b) providing or accepting any kind of compensation or incentive.</li>
              <li>You may not use any software, device or automated process, or any similar or equivalent manual process to scrape, copy or perform measurement, analysis, or monitoring of, any portion of the CineCertified logbook app or its content.</li>
              <li>You may not tamper with or circumvent any security technology included within the CineCertified logbook app.</li>
              <li>You may access the content only using the CineCertified logbook app, and may not modify or use modified versions of the content.</li>
              <li>You may not recreate, distribute or disseminate any of the content of the CineCertified logbook app unless explicitly authorised in writing by CineCertified.</li>
              <li>It is your responsibility to keep your CineCertified account and your completion of the CineCertified logbook app accurate and up-to-date.</li>
              <li>It is your responsibility to undertake research and training into all camera skills, including their key learning points, and other aspects of the CineCertified logbook app. CineCertified is not responsible for motivating you to undertake research and training into your career.</li>
              <li>You must understand a key learning point before ticking it off in the CineCertified logbook app. Demonstrating that you hold such knowledge incorrectly is a direct misuse of the CineCertified logbook app and the CineCertified training framework. Misrepresenting your level of competency may result in your CineCertified account being suspended.</li>
              <li>You must complete all aspects of the digital logbook before applying for a final assessment.</li>
              <li>It is your responsibility to find work. CineCertified is in no way responsible for finding you work or applying for jobs on your behalf.</li>
              <li>You must not create multiple or false accounts; falsify progress or sign-offs; upload harmful, misleading, or offensive material; scrape, extract, or copy data from the App; interfere with security or attempt unauthorised access; or distribute or resell any part of the App or its Content.</li>
              <li>You understand that CineCertified holds no responsibility for finding work for users of the App. Whilst the App is used for educational purposes in obtaining work, CineCertified is not a diary service, agency or a company that is in the market of offering work to its users.</li>
            </ul>

            <p className="font-bold text-white mb-2">For Signatory Users, the additional terms are also applicable:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>It is your responsibility to confirm that you are eligible to sign off on a particular stage of a camera skill.</li>
              <li>You must understand that the stages of a camera skill may only be signed off in the order of: See, Do, Teach. You may only sign off on one stage of each camera skill for an individual.</li>
              <li>In signing off a user for a stage of a camera skill, it is your responsibility to ensure that the user in question meets the appropriate level of knowledge to be signed off.</li>
              <li>It is your responsibility to make an assessment of a user’s competency when agreeing to sign them off. You are responsible for ensuring that the user understands all the key learning points of a stage of a camera skill before agreeing to sign off.</li>
              <li>You should actively engage with trainee users and encourage an open discussion about any skills and answer any questions raised, wherever possible.</li>
            </ul>

            {/* 6. INTEGRITY AND MISUSE OF TRUST */}
            <h2 className="text-2xl font-bold text-[#FAB614] mt-12 mb-6 uppercase">6. INTEGRITY AND MISUSE OF TRUST</h2>
            <p>
              The CineCertified framework is founded on trust, honesty, and professional integrity. By using the App, you agree to uphold these principles at all times. You must not misuse or abuse the system, abiding by, but not limited, to:
            </p>
            <ul className="space-y-2 pl-6">
              <li>i) creating multiple or false accounts under your own name or another person’s name;</li>
              <li>ii) falsifying or fabricating logbook entries, experience records, or training progress;</li>
              <li>iii) signing yourself off on skills or competencies;</li>
              <li>iiii) impersonating colleagues, supervisors, or signatories;</li>
              <li>v) providing false information regarding the length, nature, or details of work engagements; or</li>
              <li>vi) otherwise manipulating data or misrepresenting your experience or achievements.</li>
            </ul>
            <p>
              CineCertified relies on honesty and will not be held accountable for any false or misleading information submitted by users.
            </p>

            {/* 7. TERMINATION AND SUSPENSION OF SERVICES */}
            <h2 className="text-2xl font-bold text-[#FAB614] mt-12 mb-6 uppercase">7. TERMINATION AND SUSPENSION OF SERVICES</h2>
            <p>
              If CineCertified is notified of, or reasonably believes that you have engaged in, any form of misuse or dishonest behaviour, or that you have failed to comply with any of the provisions of this Agreement, we reserve the right, at our sole discretion, to:
            </p>
            <ul className="space-y-2 pl-6">
              <li>i) immediately suspend or permanently block your access to the App;</li>
              <li>ii) remove you from the CineCertified database and community; and</li>
              <li>iii) withdraw or invalidate any training records or recognition obtained through misuse.</li>
            </ul>
            <p>
              CineCertified further reserves the right to modify, suspend, or discontinue the Services (or any part or Content thereof) at any time with or without notice to you, and CineCertified will not be liable to you or to any third party should it exercise such rights.
            </p>
            <p>
              You may terminate your account at any time by contacting <a href="mailto:info@cinecertified.org" className="text-[#FAB614] hover:underline">info@cinecertified.org</a>.
            </p>

            {/* 8. CONTENT AND INTELLECTUAL PROPERTY */}
            <h2 className="text-2xl font-bold text-[#FAB614] mt-12 mb-6 uppercase">8. CONTENT AND INTELLECTUAL PROPERTY</h2>
            <p>
              All ‘CineCertified Content’, including, but not limited to: materials, information, data, text, images, graphics, logos, audio, video, design elements, code, and documentation, made available through the App or the CineCertified Website remains the exclusive property of CineCertified CIC or its licensors. The CineCertified name, logo and associated trademarks are protected by copyright, trademark and intellectual property laws. You may not copy, distribute, reproduce, or use any CineCertified Content except as expressly permitted within this Agreement.
            </p>
            <p>
              Using the Logbook App requires you to create a CineCertified Account. It is your responsibility to ensure that the details of your account are truthful and kept up to date. You are responsible for maintaining the confidentiality and security of your account. CineCertified is not responsible for any losses arising from the unauthorised use of your account. If you suspect that your account security has been compromised, you should contact a CineCertified administrator.
            </p>
            <p>
              You retain ownership of all materials that you upload, submit, or create through the App (“User Content”). By submitting User Content, you grant CineCertified CIC a worldwide, royalty-free, perpetual, and non-exclusive licence to use, store, reproduce, adapt, and display such content for the purposes of the operation, maintenance, development, promotion for and improvement of the CineCertified App, its training framework, and related services.
            </p>
            <p>
              You represent and warrant that you have all rights, permissions, and licences necessary to upload and share your User Content and that it does not infringe or violate any intellectual-property, privacy, or other rights of any third party.
            </p>
            <p>
              By using the App, you agree that you will not upload or distribute any User Content that infringes the rights of others, breaches confidentiality, violates data protection laws, or includes unlawful or offensive material.
            </p>
            <p>
              You are granted a limited, non-exclusive licence to access and use CineCertified Content solely for your own educational and non-commercial purposes within the CineCertified framework. You may not copy, reproduce, distribute, modify, or create derivative works from CineCertified Content except where expressly permitted by this Agreement or with our prior written consent.
            </p>

            {/* 9. YOUR SUBMISSIONS TO OUR SERVICES */}
            <h2 className="text-2xl font-bold text-[#FAB614] mt-12 mb-6 uppercase">9. YOUR SUBMISSIONS TO OUR SERVICES</h2>
            <p>
              Our services allow you to submit or post materials such as comments, ratings, reviews and pictures. Your use of such features must comply with the submissions guidelines below, which may be updated from time to time, and if we become aware of materials that violate our submission guidelines we will remove them.
            </p>
            <p>
              If you see materials that do not comply with the submissions guidelines, including any offensive, abusive, or illegal content, please let us know at <a href="mailto:info@cinecertified.org" className="text-[#FAB614] hover:underline">info@cinecertified.org</a>.
            </p>
            <p>You may not use the services to:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>upload or post any materials that (i) you do not have permission, right or license to use, or (ii) infringe on the rights of any third party;</li>
              <li>upload or post objectionable, offensive, distasteful, unlawful, hateful, harmful, deceptive, infringing, inaccurate, or otherwise inappropriate content;</li>
              <li>upload or post personal, private or confidential information belonging to others;</li>
              <li>request personal information from a minor;</li>
              <li>impersonate or misrepresent your affiliation with another person, or entity;</li>
              <li>post or transmit spam, including but not limited to unsolicited or unauthorized advertising, promotional materials, or informational announcements;</li>
              <li>upload or post, modify, or remove a rating or review in exchange for any kind of compensation or incentive;</li>
              <li>upload or post a dishonest, abusive, harmful, misleading, or bad-faith rating or review, or a rating or review that is irrelevant to the content being reviewed; or</li>
              <li>plan or engage in any illegal, fraudulent, or manipulative activity.</li>
            </ul>
            <p>
              CineCertified reserves the right, at its sole discretion and without notice, to remove, restrict, or disable access to any User Content that it believes violates this Agreement or may otherwise be unlawful, offensive, or misleading.
            </p>
            <p>
              CineCertified accepts no responsibility or liability for any errors, omissions, loss, or misuse arising from User Content uploaded or distributed through the App. Users remain fully responsible for the accuracy, legality, and reliability of the materials they provide.
            </p>

            {/* 10. SEARCH RESULTS AND RANKINGS */}
            <h2 className="text-2xl font-bold text-[#FAB614] mt-12 mb-6 uppercase">10. SEARCH RESULTS AND RANKINGS</h2>
            <p>
              By creating a CineCertified Account and using the Digital Logbook App, you consent to the inclusion of your name, contact details, professional information, photo likeness, and any materials or documents you choose to upload – such as your CV or portfolio – being displayed within the Trainee and Signatory Databases accessible through the CineCertified App and the CineCertified website. You are solely responsible for ensuring that all information submitted to your profile is complete, accurate, and truthful at all times, and for promptly updating it when changes occur.
            </p>
            <p>
              The visibility and ranking of users within the CineCertified Database are determined primarily by the metadata provided by users, the completeness of their profiles, and whether they have successfully passed the CineCertified Final Exam, thereby achieving full CineCertified status. By default, search results within the Database are displayed alphabetically; however, individuals who have achieved CineCertified status will appear at the top of all relevant search results and category listings. This arrangement is intended solely to recognise verified users who have completed CineCertified’s formal assessment process.
            </p>
            <p>
              CineCertified CIC does not verify or guarantee the accuracy, completeness, or reliability of any user-generated information contained within the Database. The information displayed is based on data supplied by users themselves and, where applicable, by members of the CineCertified community who provide sign-offs or endorsements. CineCertified accepts no liability for any errors, omissions, misrepresentations, or false submissions, whether intentional or inadvertent, made by users or third parties.
            </p>
            <p>
              By maintaining an account, you acknowledge that the display of your information within the CineCertified Database is subject to these conditions, and that CineCertified reserves the right to modify or remove any user profile or listing at its discretion if information is found to be inaccurate, misleading, or in breach of this Agreement.
            </p>

            {/* 11. SERVICE AVAILABILITY */}
            <h2 className="text-2xl font-bold text-[#FAB614] mt-12 mb-6 uppercase">11. SERVICE AVAILABILITY</h2>
            <p>
              Terms found in this agreement that relate to services, content types, features or functionality not available in the United Kingdom are not applicable to you unless and until they become available to you. Certain services and content available to you in the United Kingdom may not be available to you when traveling outside of your United Kingdom.
            </p>

            {/* 12. DATA PROTECTION AND PRIVACY */}
            <h2 className="text-2xl font-bold text-[#FAB614] mt-12 mb-6 uppercase">12. DATA PROTECTION AND PRIVACY</h2>
            <p>
              CineCertified CIC acts as the Data Controller for all personal data (“Personal Data”) processed through the CineCertified App and its associated services. All Personal Data is collected, stored, and processed in accordance with the UK General Data Protection Regulation (UK GDPR), the Data Protection Act 2018, and the principles set out in CineCertified’s published Privacy Policy, available at <a href="https://www.cinecertified.org/privacypolicy" className="text-[#FAB614] hover:underline">www.cinecertified.org/privacypolicy</a>.
            </p>
            <p>
              CineCertified retains Personal Data only for as long as necessary to fulfil the purposes described herein or to comply with legal obligations, after which such data will be securely deleted or anonymised.
            </p>
            <p>
              By creating a CineCertified Account and using the App, the User acknowledges and consents to the processing of their Personal Data within the United Kingdom for purposes directly related to the operation, development, and maintenance of the CineCertified framework and its training systems. Personal Data collected through the App may include, but is not limited to, the User’s name, contact details, user identifiers, training records, experience records, logbook entries, feedback, and any other materials or information submitted through their User Profile.
            </p>
            <p>
              Users’ Personal Data is processed for legitimate and specific purposes, including the creation and management of their account, verification of your training and professional experience, maintenance of accurate industry records, facilitation of sign-offs and feedback, and continuous improvement of the CineCertified App and wider framework. CineCertified may also use aggregated and anonymised data to analyse usage trends and improve service quality, but such data will not personally identify (a) user(s).
            </p>
            <p>
              CineCertified employs reasonable administrative, technical, and organisational measures designed to safeguard Users’ Personal Data against accidental or unlawful destruction, loss, alteration, unauthorised disclosure, or access. These measures include secure servers, encrypted connections, restricted access, and regular system monitoring. However, no data-transmission or storage system can be guaranteed to be completely secure, and CineCertified cannot accept liability for unauthorised access or breaches beyond its reasonable control.
            </p>
            <p>
              Users remain responsible for maintaining the confidentiality of their account credentials and for ensuring that any Personal Data they provide is accurate, current, and complete. CineCertified will not be liable for any loss or damage arising from their failure to safeguard your account information or from unauthorised activity resulting from such failure.
            </p>
            <p>
              Users have the right to access, rectify, or request deletion of your Personal Data at any time. They may also object to or restrict specific types of processing as permitted under applicable law. Requests concerning their data, or any questions regarding CineCertified’s privacy practices, can be submitted by contacting <a href="mailto:admin@cinecertified.org" className="text-[#FAB614] hover:underline">admin@cinecertified.org</a>.
            </p>
            <p>
              Further details on how CineCertified collects, processes, stores, and protects Users’ information, along with their rights under Data Protection law, are set out in the CineCertified Privacy Policy, which forms an integral part of this Agreement and should be read in conjunction with it.
            </p>

            {/* 13. PAYMENTS AND THIRD-PARTY COURSES */}
            <h2 className="text-2xl font-bold text-[#FAB614] mt-12 mb-6 uppercase">13. PAYMENTS AND THIRD-PARTY COURSES</h2>
            <p>
              The CineCertified App itself does not require any paid subscription or direct payment to access its features. However, users may be offered the opportunity to participate in professional development courses or additional optional training courses delivered by independent third-party providers, including but not limited to the Train2Save First Aid Course and the Mark Milsome Health & Safety Course (collectively referred to as “Third-Party Courses”). These courses are entirely separate from CineCertified CIC and are provided under the sole responsibility of their respective providers.
            </p>
            <p>
              All payments are processed securely via third-party payment processors compliant with PCI DSS standards; CineCertified does not store full payment card details.
            </p>
            <p>
              Any registration, payment, participation, or certification associated with Third-Party Courses is governed exclusively by the terms, conditions, and privacy policies of those providers. CineCertified acts only as an introducer, providing access or links for your convenience and professional development, and is not a contracting party to any transaction you may enter into with such providers. By enrolling in or purchasing a Third-Party Course, you acknowledge that your relationship and any associated rights or obligations exist solely between you and the provider of that course.
            </p>
            <p>
              CineCertified takes reasonable steps to ensure the security of these transactions but cannot be held liable for failures of third-party systems beyond its control. CineCertified does not verify or warrant the accuracy, quality, safety, or suitability of any third-party training materials, instructors, or course outcomes.
            </p>
            <p>
              To the fullest extent permitted by law, CineCertified disclaims all responsibility and liability arising from or related to your participation in, reliance upon, or interaction with any Third-Party Course or provider. Users are strongly encouraged to review the relevant provider’s Terms & Conditions and Privacy Policy before engaging in any external training activity.
            </p>

            {/* 14. APP STORE AND PLAY STORE COMPLIANCE */}
            <h2 className="text-2xl font-bold text-[#FAB614] mt-12 mb-6 uppercase">14. APP STORE AND PLAY STORE COMPLIANCE</h2>
            <p>
              The CineCertified App is made available for download through both the Apple App Store and the Google Play Store. By installing or using the App, you agree that your access and use of it must also comply with the applicable platform’s terms and conditions, including the Apple Media Services Terms and Conditions (<a href="https://www.apple.com/legal/internet-services/itunes/" target="_blank" rel="noopener noreferrer" className="text-[#FAB614] hover:underline">https://www.apple.com/legal/internet-services/itunes/</a>) and the Google Play Terms of Service (<a href="https://play.google.com/about/play-terms/" target="_blank" rel="noopener noreferrer" className="text-[#FAB614] hover:underline">https://play.google.com/about/play-terms/</a>). Your use of the App is therefore subject to both this Agreement and the rules of the platform from which you obtained it.
            </p>
            <p>
              If the App has been downloaded via the Apple App Store, you acknowledge that this Agreement is entered into solely between you and CineCertified CIC, and not with Apple Inc.. Apple Inc. is not responsible for the operation, maintenance, or support of the App, nor for any claims, losses, liabilities, or damages arising out of its use or performance. Likewise, if obtained via the Google Play Store, your contract remains with CineCertified CIC and not with Google LLC.
            </p>
            <p>
              You understand and agree that Apple Inc. and Google LLC are deemed third-party beneficiaries of this Agreement. Accordingly, each of these companies has the right (and will be deemed to have accepted the right) to enforce the relevant terms of this Agreement against you as a third-party beneficiary where necessary to protect their respective interests or compliance obligations.
            </p>
            <p>
              CineCertified alone is responsible for providing any necessary user support or technical assistance relating to the App and for addressing any claims you or a third party may have in connection with the App, including but not limited to: product liability, consumer protection, privacy, or regulatory compliance. Neither Apple Inc. nor Google LLC bears any responsibility for such matters.
            </p>
            <p>
              By downloading or using the App, you confirm your understanding that CineCertified CIC, and not the respective app-store operator, is solely accountable for the App’s content, functionality, and compliance with applicable law.
            </p>

            {/* 15. DISCLAIMERS */}
            <h2 className="text-2xl font-bold text-[#FAB614] mt-12 mb-6 uppercase">15. DISCLAIMERS</h2>
            <p>
              The CineCertified App and all related Services are provided to you strictly on an “as is” and “as available” basis, without warranties, guarantees, or representations of any kind, whether express or implied. To the fullest extent permitted by law, CineCertified CIC disclaims all warranties and conditions, including but not limited to implied warranties of merchantability, fitness for a particular purpose, title, accuracy, quiet enjoyment, and non-infringement.
            </p>
            <p>
              CineCertified does not warrant or represent that the App or any associated Services will operate without interruption or error, that any defects will be corrected, or that the App will be compatible with all devices, operating systems, or configurations. You acknowledge that access to and use of the App may occasionally be interrupted or affected by maintenance, updates, technical issues, or circumstances beyond CineCertified’s control.
            </p>
            <p>
              CineCertified makes no guarantees regarding the accuracy, completeness, or reliability of any User Content, sign-off data, verification records, or information stored in or generated by the App’s database. All such information is user-generated, and CineCertified is not responsible for verifying the truth or authenticity of entries submitted by users or third parties.
            </p>
            <p>
              Training progress, “Professional Development”, “Ancillary Learning” and employment outcomes achieved through use of the CineCertified framework are entirely the responsibility of the individual user. CineCertified does not guarantee work placements, training opportunities, or certification results, and any reliance on App data or other users’ submissions is at your own discretion and risk.
            </p>
            <p>
              It is your sole responsibility to maintain the security of your personal devices, networks, and backup copies of any important information or materials you upload to or generate through the App. CineCertified accepts no liability for loss, corruption, or unauthorised access to your data caused by device failure, user negligence, or external technical issues beyond our reasonable control.
            </p>

            {/* 16. GOVERNING LAW AND JURISDICTION */}
            <h2 className="text-2xl font-bold text-[#FAB614] mt-12 mb-6 uppercase">16. GOVERNING LAW AND JURISDICTION</h2>
            <p>
              This Agreement, and any dispute, claim, or obligation arising out of or in connection with it, whether contractual or non-contractual, shall be governed by and construed in accordance with the laws of England and Wales, without regard to conflict-of-law principles that might direct the application of another jurisdiction’s laws.
            </p>
            <p>
              By accessing or using the CineCertified App, and its services, you acknowledge and agree that any dispute or claim arising from or related to this Agreement, your use of the App, or the Services shall be subject to the exclusive jurisdiction of the courts of London, United Kingdom. You consent to the personal jurisdiction of those courts for all such matters and waive any objection to the venue or forum on the basis of inconvenience.
            </p>
            <p>
              If you reside in the European Union, you may alternatively bring proceedings in your country of residence where consumer-protection legislation provides such a right. If you reside in the United States or in any other country outside the United Kingdom or the European Union, you agree that this Agreement shall continue to be governed by the laws of England and Wales, and that any dispute shall be resolved exclusively before the courts of London, United Kingdom, to the fullest extent permitted by applicable local law.
            </p>
            <p>
              The application of the United Nations Convention on Contracts for the International Sale of Goods (CISG) is expressly excluded.
            </p>

            {/* 17. LICENCING */}
            <h2 className="text-2xl font-bold text-[#FAB614] mt-12 mb-6 uppercase">17. LICENCING</h2>
            <p>
              To the fullest extent permitted by applicable law, CineCertified CIC, (including its directors, officers, employees, contractors, licensors, and partners) shall not be liable for personal injury or any indirect, incidental, consequential, exemplary, or punitive damages, or for any loss of profits, revenue, data, goodwill, opportunity, or business, whether arising in contract, tort (including negligence), equity, statute, or otherwise, even if CineCertified has been advised of the possibility of such damages. This includes, without limitation, any loss or damage resulting from: (a) your access to, use of, or inability to access or use the app or related services; (b) reliance upon any information, record, or content obtained through the app; (c) unauthorised access to or use of your account, data, or device; (d) hacking, viruses, or security breaches beyond CineCertified’s reasonable control; or (e) errors, omissions, interruptions, corruptions, delays, transmission failures, or system faults.
            </p>
            <p>
              CineCertified shall not be responsible for any damage or loss arising from your failure to maintain adequate data backups or to follow recommended security practices. You acknowledge that the app is provided for educational and professional development purposes only, and you assume full responsibility for your use of the app and any consequences arising from it.
            </p>
            <p>
              In any event, and notwithstanding any provision to the contrary, CineCertified’s total aggregate liability to you for all claims, damages, losses, and causes of action arising out of or in connection with this Agreement or your use of the App shall not exceed two hundred and fifty Great British Pounds (£250).
            </p>
            <p>
              Nothing in this Agreement shall limit or exclude liability for death or personal injury caused by negligence, fraud or fraudulent misrepresentation, or any other liability which cannot be excluded or limited under UK law.
            </p>
            <p>
              You agree to indemnify, defend, and hold harmless CineCertified CIC, its officers, directors, employees, contractors, and affiliates from and against any and all claims, liabilities, losses, damages, costs, or expenses (including reasonable legal fees) arising from or related to your breach of this Agreement, misuse of the App, or violation of any applicable law or third-party rights.
            </p>

            {/* 18. WAIVER AND INDEMNITY */}
            <h2 className="text-2xl font-bold text-[#FAB614] mt-12 mb-6 uppercase">18. WAIVER AND INDEMNITY</h2>
            <p>
              By using the services of the App, you agree, to the extent permitted by law, to indemnify and hold CineCertified, its directors, officers, employees, affiliates, agents, contractors, and licensors, harmless with respect to any claims arising out of your breach of this agreement, your use of the services, or any action taken by CineCertified as part of its investigation of a suspected violation of this agreement or as a result of its finding or decision that a violation of this agreement has occurred.
            </p>
            <p>
              You agree that you shall not sue (or attempt to sue) or recover any damages from CineCertified, its directors, officers, employees, affiliates, agents, contractors, and licensors as a result of its decision to remove or deny access to any information or content, to suspend or terminate your access to the services, or to take any other action during the investigation of a suspected violation or as a result of CineCertified’s conclusion that a violation of this agreement has occurred. This waiver and indemnity provision applies to all violations described in or contemplated by this agreement.
            </p>

            {/* 19. MODIFICATIONS */}
            <h2 className="text-2xl font-bold text-[#FAB614] mt-12 mb-6 uppercase">19. MODIFICATIONS</h2>
            <p>
              CineCertified reserves the right to modify, revise, or update these Terms and Conditions at any time in order to reflect changes in law, regulatory guidance, operational practices, or enhancements to the CineCertified App and its Services. Any such updates or amendments will take effect immediately upon being posted within the App or published on the official CineCertified website at <a href="https://www.cinecertified.org" className="text-[#FAB614] hover:underline">www.cinecertified.org</a>.
            </p>
            <p>
              CineCertified will take reasonable steps to notify users of material changes where required by law, such as by email notification, pop-up message, or notice within the App. However, it remains your responsibility to review these Terms periodically to ensure you are familiar with the most current version.
            </p>
            <p>
              Your continued access to or use of the App after any updates have been published shall constitute your full acceptance of the revised Terms and your agreement to be bound by them. If you do not agree to any modification, you must immediately discontinue use of the App and, if applicable, request closure of your CineCertified Account.
            </p>

            {/* 20. OTHER PROVISIONS */}
            <h2 className="text-2xl font-bold text-[#FAB614] mt-12 mb-6 uppercase">20. OTHER PROVISIONS</h2>
            <p>
              This agreement constitutes the entire agreement between you and CineCertified and governs your use of the services, superseding any prior agreements with respect to the same subject matter between you and CineCertified. You also may be subject to additional terms and conditions that may apply when you make transactions or use affiliate services, third-party content, third-party software. If any part of this agreement is held invalid or unenforceable, that portion shall be construed in a manner consistent with applicable law to reflect, as nearly as possible, the original intentions of the parties, and the remaining portions shall remain in full force and effect. CineCertified’s failure to enforce any right or provisions in this agreement will not constitute a waiver of such or any other provision. CineCertified will not be responsible for failures to fulfill any obligations due to causes beyond its control.
            </p>
            <p>
              You agree to comply with all laws, statutes, ordinances, and regulations that apply to your use of the services. Your use of the services may also be subject to other laws. Risk of loss for all electronically delivered transactions are passed to the acquirer upon electronic transmission to the recipient. No CineCertified employee, agent, or representative has the authority to vary this agreement.
            </p>
            <p>
              CineCertified may notify you with respect to the services by sending an email message to your email address, text message (including SMS and MMS) to your phone number, or a letter via postal mail to your mailing address, or by a posting on their services or online accounts, including Social Media accounts. Notices shall become effective immediately. CineCertified may also contact you by email or push notification to send you additional information about the services.
            </p>
            <p>
              You hereby grant CineCertified the right to take steps that CineCertified believes are reasonably necessary or appropriate to enforce and/or verify compliance with any part of this agreement. You agree that CineCertified has the right, without liability to you, to disclose any data and/or information to law enforcement authorities, government officials, and/or a third party, as CineCertified believes is reasonably necessary or appropriate to enforce and/or verify compliance with any part of this agreement (including but not limited to: CineCertified’s right to cooperate with any legal process relating to your use of the Services and/or Content, and/or a third-party claim that your use of the Services and/or Content is unlawful and/or infringes such third party’s rights).
            </p>

            {/* 21. NOTICES AND CONTACT */}
            <h2 className="text-2xl font-bold text-[#FAB614] mt-12 mb-6 uppercase">21. NOTICES AND CONTACT</h2>
            <p>
              All legal notices, questions, or formal requests relating to these Terms, your account, or the CineCertified App should be directed to CineCertified using the contact details below. Notices shall be deemed received once properly delivered by email or post to the specified address.
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>By Post: CineCertified CIC, Flat 4, 34 Churchfield Road, London W3 6EB, United Kingdom</li>
              <li>By Email: <a href="mailto:admin@cinecertified.org" className="text-[#FAB614] hover:underline">admin@cinecertified.org</a></li>
              <li>Via Website: <a href="https://www.cinecertified.org" className="text-[#FAB614] hover:underline">www.cinecertified.org</a></li>
            </ul>
            <p>
              CineCertified may contact you regarding updates, account verification, or legal notifications through the App, by email, or via other reasonable means. You agree that such electronic communications satisfy any legal requirement that communications be made in writing.
            </p>

            {/* 22. ENTIRE AGREEMENT */}
            <h2 className="text-2xl font-bold text-[#FAB614] mt-12 mb-6 uppercase">22. ENTIRE AGREEMENT</h2>
            <p>
              This Agreement constitutes the entire understanding between you and CineCertified CIC concerning your use of the CineCertified App and related Services. It supersedes and replaces all prior or contemporaneous representations, discussions, agreements, proposals, or communications, whether written or oral, relating to the same subject matter.
            </p>
            <p>
              If any provision of this Agreement is held to be invalid, illegal, or unenforceable by a court or competent authority, that provision shall be enforced to the maximum extent permissible, and the remaining provisions shall remain in full force and effect. No failure or delay by CineCertified in enforcing any provision of this Agreement shall constitute a waiver of its rights.
            </p>

            <p className="mt-12 text-gray-500 italic">Last Updated: November 11, 2025</p>

          </div>
        </div>
      </div>

      <Footer />
    </div>
  );
};

export default TermsPage;